 <div class="accord">
  <div id="accordion">
  <div class="accordionMainTitle">
    <span>Frequently Asked Questions </span>
  </div>
  <div id="panel-wrapper"> 
    <div class="panel active">
     <div class="acc-header">
     <span>How do i setup my lock?</span>
    </div>
    <div class="acc-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
<div class="panel">
     <div class="acc-header">
     <span>Lorem Ipsum is simply dummy text?</span>
    </div>
    <div class="acc-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
<div class="panel">
     <div class="acc-header">
    <span class="acc-header-title">Lorem Ipsum is simply dummy text?</span>
    </div>
    <div class="acc-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
  <div class="panel">
     <div class="acc-header">
    <span class="acc-header-title">Lorem Ipsum is simply dummy text?</span>
    </div>
    <div class="acc-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
   </div>
   
</div>

<style type="text/css">
.panel {
  padding: 5px;
  
}
.accordionMainTitle {
 
  font-size: 25px;
}

.acc-header {
  cursor: pointer;
  padding: 15px;
  color: #000;
  border-radius: 5px;
  font-weight: 500;
  background-color: #FAFAFA;
  display: block;
  font-family: 'Raleway', sans-serif;
  margin-bottom:0px;
  border-bottom: none !important;
}
.acc-header span:after{

    content: '\e622';
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 10px;
    line-height: 22px;
    color: inherit;
    content: '\e622';
    font-family: 'luma-icons';
    margin: 0;
    vertical-align: top;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    text-align: center;
    float: right;
}

.acc-body {
    padding: 20px;
    line-height: 1.9;
    background-color: #FAFAFA;
    border-radius: 0 0 10px 10px;
    font-family: 'Raleway', sans-serif;
}
#accordion .acc-body{
   display : none;
}

#accordion .active .acc-body {
   display : block;
}


</style>

<script type="text/javascript">
function initAccordion(accordionElem){
  
  //when panel is clicked, handlePanelClick is called.           
  function handlePanelClick(event){
      showPanel(event.currentTarget);
  }
//Hide currentPanel and show new panel.  
  
  function showPanel(panel){
    //Hide current one. First time it will be null. 
     var expandedPanel = accordionElem.querySelector(".active");
     if (expandedPanel){
         expandedPanel.classList.remove("active");
     }
     //Show new one
     panel.classList.add("active");
     
  }
  var allPanelElems = accordionElem.querySelectorAll(".panel");
  for (var i = 0, len = allPanelElems.length; i < len; i++){
       allPanelElems[i].addEventListener("click", handlePanelClick);
  }
  //By Default Show first panel
  showPanel(allPanelElems[-1])
}
initAccordion(document.getElementById("accordion"));

var accordionHeader = document.g
</script>