<div class="slide1">
	<div class="slides slide_one">
		<h1>Bellagio Trunk</h1>
		<p>Bellagio is a classic collection of hi-tech hardside wheeled suitcases with a vintage vibe. An outside shell in polycarbonate guarantees not only lightness but also resistance to scuffing and scratching. The zip fastening has a water-repellent polyurethane finish. It has been set on 4 double swivelling super-smooth wheels fitted with ball bearings. Finished with vegetable-tanned Tuscan-leather, it boasts an impeccable aesthetic, an unimpeachably elegant design and a sophisticated colour scheme.</p>
		<button class="read_more">Learn More</button>
	</div>
	<div class="slides">
		<img src="<?php echo $this->getViewFileUrl('images/slide_1.png'); ?>">
	</div>
</div>

<div class="slide2">
  <img src="<?php echo $this->getViewFileUrl('images/slide_2.png'); ?>">
</div>
