<div>   
    <img src="<?php echo $this->getViewFileUrl('images/logo_lg.png'); ?>">
</div>
    
<div>
   <ul class="custom_menu">
      <li>
        <a href="#">Products</a>
      </li>
      <li>
        <a href="#">Collection</a>
      <li>
      <li>
        <a href="#">BIY Brand</a>
      </li>
      <li>
        <a href="#">Porsche Design</a>
      </li>
      <li>
        <a href="#">Zero Halliburton</a>
      </li>
      <li>
        <a href="#">Store Locator</a>
      </li>
    </ul>		
</div>
<div>
	<ul class="right_menu">
      <li>
        <img src="<?php echo $this->getViewFileUrl('images/right_menu_1.png'); ?>">
      </li>
      <li>
        <img src="<?php echo $this->getViewFileUrl('images/right_menu_2.png'); ?>">
      <li>
    </ul>
</div>

<script type="text/javascript">require(['bootstrap']);</script>