<footer>
<div class="container">
  <div class="row"> 
    <div class="col-lg-5 col-md-3 col-sm-12 bottom">
      <a href="#"><img src="<?php echo $this->getViewFileUrl('images/logo_lg.png'); ?>"></a>
      <strong class="social_links">FIND US ON 
      	<span><i class="fa fa-facebook" aria-hidden="true"></i></span>
      	<span><i class="fa fa-instagram" aria-hidden="true"></i></span>
      	<span><i class="fa fa-linkedin" aria-hidden="true"></i></span>
      	</strong>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-12 bottom">
      <h3><span>SHOP</span></h3>
      <ul>
        <li><a href="#" >Collection</a></li>
        <li><a href="#">BIY Brand</a></li>
        <li><a href="#">Porsche Design</a></li> 
        <li><a href="#">Store Locator</a></li>
      </ul>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-12 bottom">
      <h3><span>ABOUT US</span></h3>
      <ul>
        <li><a href="#">History</a></li>
        <li><a href="#">Work With Us</a></li>
        <li><a href="#">Contacts</a></li>
        <li><a href="#">Corporate Gift</a></li>
      </ul>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 bottom">
      <h3><span>SUBSCRIBE TO OUR NEWSLETTER</span></h3>
      <div>
        <input type="text" placeholder="Email"></input>
        <button>SUBSCRIBE</button>
      </div>
      <div class="address">
        <li><i class="fa fa-phone" aria-hidden="true"></i> Contact Us</li>
        <li><i class="fa fa-map-marker" aria-hidden="true"></i> Store Locator</li>
    </div>
 
    </div>
  </div>
 </div>
</footer>
